version: '3.8'

services:
  frontend:
    build:
      context: ./admin
    ports:
      - "9000:9000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

  backend:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm start
